senzing-garage/docker-compose-demo

README.md
=> issue-1 Improve format

docs/docker-compose-kafka-db2/README.md, docs/docker-compose-kafka-mysql/README.md, docs/docker-compose-kafka-postgresql/README.md, docs/docker-compose-rabbitmq-db2/README.md, docs/docker-compose-rabbitmq-mysql/README.md, docs/docker-compose-rabbitmq-postgresql/README.md
=> issue-1 Simply database creation

docker-compose-kafka-db2.yaml, docker-compose-kafka-mysql-v2-format.yaml, docker-compose-kafka-mysql.yaml, docker-compose-kafka-postgresql.yaml, docker-compose-kafka-sqlite.yaml, docker-compose-mysql-initialization.yaml, docker-compose-postgresql-initialization.yaml, docker-compose-rabbitmq-db2.yaml, docker-compose-rabbitmq-mysql.yaml, docker-compose-rabbitmq-postgresql.yaml, docker-compose-rabbitmq-sqlite.yaml, docker-compose-sqlite-initialization.yaml, docker-compose-sqlite2-initialization.yaml, docker-compose-url-mysql.yaml, docs/docker-compose-kafka-db2/README.md, docs/docker-compose-kafka-mysql/README.md, docs/docker-compose-kafka-postgresql/README.md, docs/docker-compose-kafka-sqlite/README.md, docs/docker-compose-rabbitmq-db2/README.md, docs/docker-compose-rabbitmq-mysql/README.md, docs/docker-compose-rabbitmq-postgresql/README.md, docs/docker-compose-rabbitmq-sqlite/README.md
=> issue-10 Add database initialization

docker-compose-mysql-initialization.yaml, docker-compose-postgresql-initialization.yaml, docker-compose-sqlite-initialization.yaml
=> issue-10 Update version of g2-configuration-initializer

CHANGELOG.md
=> issue-10 Original changelog

docs/docker-compose-kafka-postgresql/README.md, docs/docker-compose-kafka-sqlite/README.md, docs/docker-compose-rabbitmq-postgresql/README.md
=> issue-10 Minor doc fixes

CHANGELOG.md
=> Issue 16.dockter.2

README.md, docs/docker-compose-kafka-db2/README.md, docs/docker-compose-kafka-mysql/README.md, docs/docker-compose-kafka-postgresql/README.md, docs/docker-compose-kafka-sqlite/README.md, docs/docker-compose-rabbitmq-db2/README.md, docs/docker-compose-rabbitmq-mysql/README.md, docs/docker-compose-rabbitmq-postgresql/README.md, docs/docker-compose-rabbitmq-sqlite/README.md
=> issue-19 Point to web app URL

docs/docker-compose-kafka-db2/README.md, docs/docker-compose-kafka-mysql/README.md, docs/docker-compose-kafka-postgresql/README.md, docs/docker-compose-kafka-sqlite/README.md, docs/docker-compose-rabbitmq-db2/README.md, docs/docker-compose-rabbitmq-mysql/README.md, docs/docker-compose-rabbitmq-postgresql/README.md, docs/docker-compose-rabbitmq-sqlite/README.md, resources/db2/docker-compose-kafka-db2-again.yaml, resources/db2/docker-compose-kafka-db2.yaml, resources/db2/docker-compose-rabbitmq-db2-again.yaml, resources/db2/docker-compose-rabbitmq-db2.yaml, resources/mysql/docker-compose-kafka-mysql-again.yaml, resources/mysql/docker-compose-kafka-mysql.yaml, resources/mysql/docker-compose-rabbitmq-mysql-again.yaml, resources/mysql/docker-compose-rabbitmq-mysql.yaml, resources/postgresql/docker-compose-kafka-postgresql-again.yaml, resources/postgresql/docker-compose-kafka-postgresql.yaml, resources/postgresql/docker-compose-rabbitmq-postgresql-again.yaml, resources/postgresql/docker-compose-rabbitmq-postgresql.yaml, resources/sqlite/docker-compose-rabbitmq-sqlite.yaml
=> issue-19 Remove unnecessary environment variables

docs/docker-compose-rabbitmq-postgresql/README.md, resources/postgresql/docker-compose-rabbitmq-postgresql.yaml
=> issue-19 Add OpenApi browser

docs/docker-compose-kafka-db2/README.md, docs/docker-compose-kafka-mysql/README.md, docs/docker-compose-kafka-postgresql/README.md, docs/docker-compose-kafka-sqlite/README.md, docs/docker-compose-rabbitmq-db2/README.md, docs/docker-compose-rabbitmq-mysql/README.md, docs/docker-compose-rabbitmq-postgresql/README.md, docs/docker-compose-rabbitmq-sqlite/README.md, resources/db2/docker-compose-kafka-db2-again.yaml, resources/db2/docker-compose-kafka-db2.yaml, resources/db2/docker-compose-rabbitmq-db2-again.yaml, resources/db2/docker-compose-rabbitmq-db2.yaml, resources/mysql/docker-compose-kafka-mysql-again.yaml, resources/mysql/docker-compose-kafka-mysql-v2-format.yaml, resources/mysql/docker-compose-kafka-mysql.yaml, resources/mysql/docker-compose-rabbitmq-mysql-again.yaml, resources/mysql/docker-compose-rabbitmq-mysql.yaml, resources/postgresql/docker-compose-kafka-postgresql-again.yaml, resources/postgresql/docker-compose-kafka-postgresql.yaml, resources/postgresql/docker-compose-rabbitmq-postgresql-again.yaml, resources/postgresql/docker-compose-rabbitmq-postgresql.yaml, resources/sqlite/docker-compose-kafka-sqlite.yaml, resources/sqlite/docker-compose-rabbitmq-sqlite.yaml
=> issue-19 Adjusted ports

docs/docker-compose-kafka-db2/README.md, docs/docker-compose-kafka-mysql/README.md, docs/docker-compose-kafka-postgresql/README.md, docs/docker-compose-kafka-sqlite/README.md, docs/docker-compose-rabbitmq-db2/README.md, docs/docker-compose-rabbitmq-mysql/README.md, docs/docker-compose-rabbitmq-postgresql/README.md, docs/docker-compose-rabbitmq-sqlite/README.md, resources/db2/docker-compose-kafka-db2-again.yaml, resources/db2/docker-compose-kafka-db2.yaml, resources/db2/docker-compose-rabbitmq-db2-again.yaml, resources/db2/docker-compose-rabbitmq-db2.yaml, resources/mysql/docker-compose-kafka-mysql-again.yaml, resources/mysql/docker-compose-kafka-mysql.yaml, resources/mysql/docker-compose-rabbitmq-mysql-again.yaml, resources/mysql/docker-compose-rabbitmq-mysql.yaml, resources/postgresql/docker-compose-kafka-postgresql-again.yaml, resources/postgresql/docker-compose-kafka-postgresql.yaml, resources/postgresql/docker-compose-rabbitmq-postgresql-again.yaml, resources/postgresql/docker-compose-rabbitmq-postgresql.yaml, resources/sqlite/docker-compose-kafka-sqlite.yaml, resources/sqlite/docker-compose-rabbitmq-sqlite.yaml
=> issue-29 Add senzing/senzing-debug container

docs/docker-compose-kafka-db2/README.md, docs/docker-compose-kafka-mysql/README.md, docs/docker-compose-kafka-postgresql/README.md, docs/docker-compose-kafka-sqlite/README.md, docs/docker-compose-rabbitmq-db2/README.md, docs/docker-compose-rabbitmq-mysql/README.md, docs/docker-compose-rabbitmq-postgresql/README.md, docs/docker-compose-rabbitmq-sqlite/README.md
=>  issue-31 Added SENZING_VAR_DIR 

docs/docker-compose-kafka-db2/README.md, docs/docker-compose-kafka-mysql/README.md, docs/docker-compose-kafka-postgresql/README.md, docs/docker-compose-kafka-sqlite/README.md, docs/docker-compose-rabbitmq-db2/README.md, docs/docker-compose-rabbitmq-mysql/README.md, docs/docker-compose-rabbitmq-postgresql/README.md, docs/docker-compose-rabbitmq-sqlite/README.md
=> issue-36 Add instructions for g2.lic

docs/docker-compose-kafka-db2/README.md, docs/docker-compose-kafka-mysql/README.md, docs/docker-compose-kafka-postgresql/README.md, docs/docker-compose-kafka-sqlite/README.md, docs/docker-compose-rabbitmq-db2/README.md, docs/docker-compose-rabbitmq-mysql/README.md, docs/docker-compose-rabbitmq-postgresql/README.md, docs/docker-compose-rabbitmq-sqlite/README.md, resources/db2/docker-compose-kafka-db2.yaml, resources/db2/docker-compose-rabbitmq-db2.yaml, resources/mysql/docker-compose-kafka-mysql.yaml, resources/mysql/docker-compose-rabbitmq-mysql.yaml, resources/postgresql/docker-compose-kafka-postgresql.yaml, resources/postgresql/docker-compose-rabbitmq-postgresql.yaml, resources/sqlite/docker-compose-kafka-sqlite.yaml, resources/sqlite/docker-compose-rabbitmq-sqlite.yaml
=> issue-33 Update to senzing/init-container:1.3.3

CODE_OF_CONDUCT.md, CONTRIBUTING.md, PULL_REQUEST_TEMPLATE.md, docs/docker-compose-kafka-db2/README.md, docs/docker-compose-rabbitmq-db2/README.md, resources/db2/docker-compose-kafka-db2-again.yaml, resources/db2/docker-compose-kafka-db2.yaml, resources/db2/docker-compose-rabbitmq-db2-again.yaml, resources/db2/docker-compose-rabbitmq-db2.yaml
=> issue-35 Change parameter names

docs/docker-compose-kafka-db2/README.md, docs/docker-compose-kafka-mssql/README.md, docs/docker-compose-kafka-mysql/README.md, docs/docker-compose-kafka-postgresql/README.md, docs/docker-compose-kafka-sqlite/README.md, docs/docker-compose-rabbitmq-db2/README.md, docs/docker-compose-rabbitmq-mssql/README.md, docs/docker-compose-rabbitmq-mysql/README.md, docs/docker-compose-rabbitmq-postgresql/README.md, docs/docker-compose-rabbitmq-sqlite/README.md
=> issue-41 Refactor to template

CHANGELOG.md, docs/docker-compose-kafka-db2/README.md, docs/docker-compose-kafka-mysql/README.md, docs/docker-compose-kafka-postgresql/README.md, docs/docker-compose-kafka-sqlite/README.md, docs/docker-compose-rabbitmq-db2/README.md, docs/docker-compose-rabbitmq-mysql/README.md, docs/docker-compose-rabbitmq-postgresql/README.md, docs/docker-compose-rabbitmq-sqlite-cluster/README.md, docs/docker-compose-rabbitmq-sqlite/README.md, resources/sqlite-cluster/docker-compose-rabbitmq-sqlite-cluster.yaml
=> issue-44 Add SQLite Senzing cluster

resources/plugins/governor.py
=> issue-47  Demonstrate state

resources/plugins/governor.py
=> #47 Fixed output

resources/sqlite-cluster/docker-compose-rabbitmq-sqlite-cluster.yaml
=> #51 Add privileged

CHANGELOG.md
=> #60 Add version 1.3.2

docs/docker-compose-kafka-db2/README.md, docs/docker-compose-kafka-mssql/README.md, docs/docker-compose-kafka-mysql/README.md, docs/docker-compose-kafka-postgresql/README.md, docs/docker-compose-kafka-sqlite/README.md, docs/docker-compose-rabbitmq-db2/README.md, docs/docker-compose-rabbitmq-mssql/README.md, docs/docker-compose-rabbitmq-mysql/README.md, docs/docker-compose-rabbitmq-postgresql/README.md, docs/docker-compose-rabbitmq-sqlite-cluster/README.md, docs/docker-compose-rabbitmq-sqlite-governor/README.md, docs/docker-compose-rabbitmq-sqlite-jupyter/README.md, docs/docker-compose-rabbitmq-sqlite/README.md
=> #66 Remove 'Pull docker images'

README.md
=> #73 Remove SQLite references

resources/postgresql/docker-compose-kafka-postgresql-again.yaml, resources/postgresql/docker-compose-kafka-postgresql-redoer-kafka-withinfo.yaml, resources/postgresql/docker-compose-kafka-postgresql-redoer-kafka.yaml, resources/postgresql/docker-compose-kafka-postgresql-redoer-withinfo.yaml, resources/postgresql/docker-compose-kafka-postgresql-redoer.yaml, resources/postgresql/docker-compose-kafka-postgresql-withinfo.yaml, resources/postgresql/docker-compose-kafka-postgresql.yaml, resources/postgresql/docker-compose-rabbitmq-postgresql-again.yaml, resources/postgresql/docker-compose-rabbitmq-postgresql-poc.yaml, resources/postgresql/docker-compose-rabbitmq-postgresql-redoer-rabbitmq-withinfo.yaml, resources/postgresql/docker-compose-rabbitmq-postgresql-redoer-rabbitmq.yaml, resources/postgresql/docker-compose-rabbitmq-postgresql-redoer-withinfo.yaml, resources/postgresql/docker-compose-rabbitmq-postgresql-redoer.yaml, resources/postgresql/docker-compose-rabbitmq-postgresql-withinfo.yaml, resources/postgresql/docker-compose-rabbitmq-postgresql.yaml, resources/sqlite/docker-compose-kafka-sqlite.yaml, resources/sqlite/docker-compose-rabbitmq-sqlite-cluster.yaml, resources/sqlite/docker-compose-rabbitmq-sqlite-debug.yaml, resources/sqlite/docker-compose-rabbitmq-sqlite-governor.yaml, resources/sqlite/docker-compose-rabbitmq-sqlite-redoer.yaml, resources/sqlite/docker-compose-rabbitmq-sqlite.yaml, resources/sqlite/docker-compose-resolver.yaml
=> issue-75 move to senzing/postgresql-client

docs/docker-compose-kafka-mysql/README.md, docs/docker-compose-kafka-postgresql/README.md, docs/docker-compose-rabbitmq-mysql/README.md
=> #73 Fix referencs to SQLite

resources/db2/docker-compose-kafka-db2.yaml, resources/db2/docker-compose-rabbitmq-db2.yaml, resources/mssql/docker-compose-kafka-mssql.yaml, resources/mssql/docker-compose-mssql-driver.yaml, resources/mssql/docker-compose-rabbitmq-mssql.yaml, resources/mysql/docker-compose-kafka-mysql.yaml, resources/mysql/docker-compose-rabbitmq-mysql.yaml, resources/postgresql/docker-compose-kafka-postgresql-redoer-kafka-withinfo.yaml, resources/postgresql/docker-compose-kafka-postgresql-redoer-kafka.yaml, resources/postgresql/docker-compose-kafka-postgresql-redoer-withinfo.yaml, resources/postgresql/docker-compose-kafka-postgresql-redoer.yaml, resources/postgresql/docker-compose-kafka-postgresql-withinfo.yaml, resources/postgresql/docker-compose-kafka-postgresql.yaml, resources/postgresql/docker-compose-rabbitmq-postgresql-poc.yaml, resources/postgresql/docker-compose-rabbitmq-postgresql-redoer-rabbitmq-withinfo.yaml, resources/postgresql/docker-compose-rabbitmq-postgresql-redoer-rabbitmq.yaml, resources/postgresql/docker-compose-rabbitmq-postgresql-redoer-withinfo.yaml, resources/postgresql/docker-compose-rabbitmq-postgresql-redoer.yaml, resources/postgresql/docker-compose-rabbitmq-postgresql-withinfo.yaml, resources/postgresql/docker-compose-rabbitmq-postgresql.yaml, resources/sqlite/docker-compose-kafka-sqlite.yaml, resources/sqlite/docker-compose-rabbitmq-sqlite-cluster.yaml, resources/sqlite/docker-compose-rabbitmq-sqlite-debug.yaml, resources/sqlite/docker-compose-rabbitmq-sqlite-governor.yaml, resources/sqlite/docker-compose-rabbitmq-sqlite-redoer.yaml, resources/sqlite/docker-compose-rabbitmq-sqlite.yaml, resources/sqlite/docker-compose-resolver.yaml
=> #79 Upgrade to senzing/init-container:1.5.2

CHANGELOG.md
=> #96 Prepare for version

README.md, docs/docker-compose-kafka-db2/README.md, docs/docker-compose-kafka-mssql/README.md, docs/docker-compose-kafka-mysql/README.md, docs/docker-compose-kafka-postgresql-advanced/README.md, docs/docker-compose-kafka-postgresql/README.md, docs/docker-compose-kafka-sqlite/README.md, docs/docker-compose-rabbitmq-db2/README.md, docs/docker-compose-rabbitmq-mssql/README.md, docs/docker-compose-rabbitmq-mysql/README.md, docs/docker-compose-rabbitmq-postgresql-advanced/README.md, docs/docker-compose-rabbitmq-postgresql/README.md, docs/docker-compose-rabbitmq-sqlite-advanced/README.md, docs/docker-compose-rabbitmq-sqlite-cluster/README.md, docs/docker-compose-rabbitmq-sqlite-governor/README.md, docs/docker-compose-rabbitmq-sqlite/README.md, docs/docker-compose-sqs-postgresql-advanced/README.md, docs/docker-compose-sqs-postgresql/README.md
=> update to new senzing-rest-api-specification url

resources/postgresql/docker-compose-rabbitmq-postgresql.yaml
=> #101 Add environment variables to entity-search-web-app

resources/db2/docker-compose-kafka-db2-again.yaml, resources/db2/docker-compose-kafka-db2.yaml, resources/db2/docker-compose-rabbitmq-db2-again.yaml, resources/db2/docker-compose-rabbitmq-db2.yaml, resources/mssql/docker-compose-kafka-mssql-again.yaml, resources/mssql/docker-compose-kafka-mssql.yaml, resources/mssql/docker-compose-rabbitmq-mssql-again.yaml, resources/mssql/docker-compose-rabbitmq-mssql.yaml, resources/mysql/docker-compose-kafka-mysql-again.yaml, resources/mysql/docker-compose-kafka-mysql.yaml, resources/mysql/docker-compose-rabbitmq-mysql-again.yaml, resources/mysql/docker-compose-rabbitmq-mysql.yaml, resources/postgresql/docker-compose-kafka-postgresql-again.yaml, resources/postgresql/docker-compose-kafka-postgresql-withinfo.yaml, resources/postgresql/docker-compose-kafka-postgresql.yaml, resources/postgresql/docker-compose-rabbitmq-postgresql-again.yaml, resources/postgresql/docker-compose-rabbitmq-postgresql-poc.yaml, resources/postgresql/docker-compose-rabbitmq-postgresql-withinfo.yaml, resources/postgresql/docker-compose-sqs-postgresql-withinfo.yaml, resources/postgresql/docker-compose-sqs-postgresql.yaml
=> #101 Clean up whitespace

CHANGELOG.md
=> #105 Prepare for version

resources/postgresql/docker-compose-sqs-postgresql-redoer-sqs-withinfo.yaml, resources/postgresql/docker-compose-sqs-postgresql-redoer-sqs.yaml, resources/postgresql/docker-compose-sqs-postgresql-redoer-withinfo.yaml, resources/postgresql/docker-compose-sqs-postgresql-redoer.yaml, resources/postgresql/docker-compose-sqs-postgresql-withinfo.yaml, resources/postgresql/docker-compose-sqs-postgresql.yaml
=> #118 Add AWS_SESSION_TOKEN

docs/docker-compose-sqs-postgresql-advanced/README.md, resources/postgresql/docker-compose-rabbitmq-postgresql-debug.yaml
=> #127 New docker-compose formation

resources/db2/docker-compose-rabbitmq-db2.yaml, resources/mssql/docker-compose-rabbitmq-mssql-again.yaml, resources/postgresql/docker-compose-kafka-postgresql-redoer-kafka.yaml, resources/postgresql/docker-compose-kafka-postgresql.yaml, resources/postgresql/docker-compose-rabbitmq-postgresql-debug.yaml, resources/sqlite/docker-compose-rabbitmq-sqlite-debug.yaml
=> Cleanup remaining old OS names

resources/db2/docker-compose-kafka-db2-again.yaml, resources/db2/docker-compose-kafka-db2.yaml, resources/db2/docker-compose-rabbitmq-db2-again.yaml, resources/db2/docker-compose-rabbitmq-db2.yaml, resources/sqlite/docker-compose-rabbitmq-sqlite-cluster.yaml
=> Issue 139.dockter.1

resources/postgresql/docker-compose-rabbitmq-postgresql-cluster.yaml
=> #134 Show how to use Postgres cluster

resources/db2/docker-compose-rabbitmq-db2-cluster.yaml, resources/mssql/docker-compose-rabbitmq-mssql-cluster.yaml
=> Clustered config examples for Db2 and mssql

docs/docker-compose-kafka-db2/README.md, docs/docker-compose-kafka-mssql/README.md, docs/docker-compose-kafka-mysql/README.md, docs/docker-compose-kafka-postgresql-advanced/README.md, docs/docker-compose-kafka-postgresql/README.md, docs/docker-compose-kafka-sqlite/README.md, docs/docker-compose-rabbitmq-db2/README.md, docs/docker-compose-rabbitmq-mssql/README.md, docs/docker-compose-rabbitmq-mysql/README.md, docs/docker-compose-rabbitmq-postgresql-advanced/README.md, docs/docker-compose-rabbitmq-postgresql/README.md, docs/docker-compose-rabbitmq-sqlite-advanced/README.md, docs/docker-compose-rabbitmq-sqlite-cluster/README.md, docs/docker-compose-rabbitmq-sqlite-governor/README.md, docs/docker-compose-rabbitmq-sqlite/README.md, docs/docker-compose-sqs-postgresql-advanced/README.md, docs/docker-compose-sqs-postgresql/README.md
=> Issue 147.macy.1

resources/db2/docker-compose-kafka-db2-again.yaml, resources/db2/docker-compose-kafka-db2.yaml, resources/mssql/docker-compose-kafka-mssql-again.yaml, resources/mssql/docker-compose-kafka-mssql.yaml, resources/mysql/docker-compose-kafka-mysql-again.yaml, resources/mysql/docker-compose-kafka-mysql.yaml, resources/postgresql/docker-compose-kafka-postgresql-again.yaml, resources/postgresql/docker-compose-kafka-postgresql-redoer-kafka-withinfo.yaml, resources/postgresql/docker-compose-kafka-postgresql-redoer-kafka.yaml, resources/postgresql/docker-compose-kafka-postgresql-redoer-withinfo.yaml, resources/postgresql/docker-compose-kafka-postgresql-redoer.yaml, resources/postgresql/docker-compose-kafka-postgresql-websocket.yaml, resources/postgresql/docker-compose-kafka-postgresql-withinfo.yaml, resources/postgresql/docker-compose-kafka-postgresql.yaml, resources/sqlite/docker-compose-kafka-sqlite.yaml
=> #158 Added KAFKA_ADVERTISED_LISTENERS

resources/db2/docker-compose-rabbitmq-db2-cluster.yaml, resources/mssql/docker-compose-rabbitmq-mssql-cluster.yaml, resources/postgresql/docker-compose-rabbitmq-postgresql-cluster.yaml, resources/sqlite/docker-compose-rabbitmq-sqlite-cluster.yaml
=> Add Jupyter container to cluster databases

resources/postgresql/docker-compose-rabbitmq-postgresql-path-based-routing.yaml
=> #167 Added path-based example

CHANGELOG.md, resources/sqlite/docker-compose-kafka-sqlite.yaml
=> #167 Prepare for version

docs/custom/docker-compose-api-app-swagger/README.md
=> Issue 182.dockter.2

docs/custom/docker-compose-api-app-swagger/README.md
=> #182 Fixed list item

docs/custom/docker-compose-api-app-swagger/README.md
=> Issue 182.dockter.3

resources/postgresql/docker-compose-rabbitmq-postgresql.yaml
=> #189 migrate from command line to environment variables

README.md
=> Issue 195.dockter.1

README.md
=> #195 Delete last paragraph

resources/postgresql/docker-compose-rabbitmq-postgresql.yaml
=> remove extra services: entry

resources/postgresql/docker-compose-rabbitmq-postgresql-migration.yaml, resources/postgresql/docker-compose-rabbitmq-postgresql-v3-migration.yaml
=> Issue 245.dockter.1

docs/docker-compose-kafka-mssql/README.md, docs/docker-compose-kafka-postgresql-advanced/README.md, docs/docker-compose-kafka-postgresql/README.md, docs/docker-compose-rabbitmq-db2/README.md, docs/docker-compose-rabbitmq-mssql/README.md, docs/docker-compose-rabbitmq-mysql/README.md, docs/docker-compose-rabbitmq-postgresql-advanced/README.md, docs/docker-compose-rabbitmq-postgresql/README.md, docs/docker-compose-rabbitmq-sqlite-advanced/README.md, docs/docker-compose-rabbitmq-sqlite/README.md, docs/docker-compose-sqs-postgresql-advanced/README.md, docs/docker-compose-sqs-postgresql/README.md
=> Issue 62.dockter.1

resources/postgresql/docker-compose-rabbitmq-postgresql-again.yaml, resources/postgresql/docker-compose-rabbitmq-postgresql.yaml
=> #250 Hardcode ELK stack image versions

resources/postgresql/docker-compose-rabbitmq-postgresql-cluster.yaml
=> #223 Updated postgres mount point

resources/db2/docker-compose-kafka-db2-again.yaml, resources/db2/docker-compose-kafka-db2-api-server.yaml, resources/db2/docker-compose-kafka-db2.yaml, resources/mssql/docker-compose-kafka-mssql-again.yaml, resources/mssql/docker-compose-kafka-mssql-api-server.yaml, resources/mssql/docker-compose-kafka-mssql.yaml, resources/mysql/docker-compose-kafka-mysql-again.yaml, resources/mysql/docker-compose-kafka-mysql-api-server.yaml, resources/mysql/docker-compose-kafka-mysql.yaml, resources/postgresql/docker-compose-kafka-postgresql-again.yaml, resources/postgresql/docker-compose-kafka-postgresql-api-server.yaml, resources/postgresql/docker-compose-kafka-postgresql-redoer-kafka-withinfo.yaml, resources/postgresql/docker-compose-kafka-postgresql-redoer-kafka.yaml, resources/postgresql/docker-compose-kafka-postgresql-redoer-withinfo.yaml, resources/postgresql/docker-compose-kafka-postgresql-withinfo.yaml, resources/postgresql/docker-compose-kafka-postgresql.yaml, resources/sqlite/docker-compose-kafka-sqlite-api-server.yaml, resources/sqlite/docker-compose-kafka-sqlite.yaml
=> Issue 255.dockter.1

docs/docker-compose-kafka-db2/README.md, docs/docker-compose-kafka-mssql/README.md, docs/docker-compose-kafka-mysql/README.md, docs/docker-compose-kafka-postgresql-advanced/README.md, docs/docker-compose-kafka-postgresql/README.md, docs/docker-compose-kafka-sqlite/README.md, docs/docker-compose-rabbitmq-db2/README.md, docs/docker-compose-rabbitmq-mssql/README.md, docs/docker-compose-rabbitmq-mysql/README.md, docs/docker-compose-rabbitmq-postgresql-advanced/README.md, docs/docker-compose-rabbitmq-postgresql/README.md, docs/docker-compose-rabbitmq-sqlite-advanced/README.md, docs/docker-compose-rabbitmq-sqlite/README.md, docs/docker-compose-sqs-postgresql-advanced/README.md, docs/docker-compose-sqs-postgresql/README.md
=> Issue 262.dockter.1

CHANGELOG.md, resources/senzing/docker-compose-senzing-installation.yaml
=> #237 Savepoint

resources/postgresql/docker-compose-rabbitmq-postgresql-debug.yaml
=> #283 Add debugging

resources/postgresql/docker-compose-rabbitmq-postgresql.yaml
=> Mirage to Jupyter Lab

resources/postgresql/docker-compose-rabbitmq-postgresql-backing-services-only.yaml
=> Issue 291.dockter.1

docs/docker-compose-kafka-db2/README.md, docs/docker-compose-kafka-mssql/README.md, docs/docker-compose-kafka-sqlite/README.md, docs/docker-compose-rabbitmq-db2/README.md, docs/docker-compose-rabbitmq-mssql/README.md, docs/docker-compose-rabbitmq-postgresql-minimal/README.md, docs/docker-compose-rabbitmq-sqlite-advanced/README.md, docs/docker-compose-rabbitmq-sqlite/README.md
=> #294 Loosen file permissions

resources/postgresql/docker-compose-rabbitmq-postgresql-backing-services-only.yaml
=> Issue 296.dockter.1

resources/postgresql/docker-compose-rabbitmq-postgresql-backing-services-only.yaml
=> #298 Add network to makefile

docs/docker-compose-kafka-db2/README.md, docs/docker-compose-kafka-mssql/README.md, docs/docker-compose-kafka-mysql/README.md, docs/docker-compose-kafka-postgresql-advanced/README.md, docs/docker-compose-kafka-postgresql/README.md, docs/docker-compose-kafka-sqlite/README.md, docs/docker-compose-rabbitmq-db2/README.md, docs/docker-compose-rabbitmq-mssql/README.md, docs/docker-compose-rabbitmq-mysql/README.md, docs/docker-compose-rabbitmq-postgresql-advanced/README.md, docs/docker-compose-rabbitmq-postgresql-minimal/README.md, docs/docker-compose-rabbitmq-postgresql/README.md, docs/docker-compose-sqs-postgresql-advanced/README.md, docs/docker-compose-sqs-postgresql/README.md, resources/db2/docker-compose-rabbitmq-db2-cluster.yaml, resources/mssql/docker-compose-rabbitmq-mssql-cluster.yaml, resources/sqlite/docker-compose-kafka-sqlite-api-server.yaml, resources/sqlite/docker-compose-kafka-sqlite.yaml, resources/sqlite/docker-compose-rabbitmq-sqlite-api-server.yaml, resources/sqlite/docker-compose-rabbitmq-sqlite-cluster.yaml, resources/sqlite/docker-compose-rabbitmq-sqlite-debug.yaml, resources/sqlite/docker-compose-rabbitmq-sqlite-governor.yaml, resources/sqlite/docker-compose-rabbitmq-sqlite.yaml
=> Issue 304.dockter.2

CHANGELOG.md, resources/postgresql/docker-compose-kafka-postgresql-api-server.yaml, resources/postgresql/docker-compose-kafka-postgresql-redoer-kafka-withinfo.yaml, resources/postgresql/docker-compose-kafka-postgresql-redoer-kafka.yaml, resources/postgresql/docker-compose-kafka-postgresql-redoer-withinfo.yaml, resources/postgresql/docker-compose-kafka-postgresql-withinfo.yaml, resources/postgresql/docker-compose-kafka-postgresql.yaml, resources/postgresql/docker-compose-rabbitmq-postgresql-api-server.yaml, resources/postgresql/docker-compose-rabbitmq-postgresql-backing-services-only.yaml, resources/postgresql/docker-compose-rabbitmq-postgresql-cluster.yaml, resources/postgresql/docker-compose-rabbitmq-postgresql-debug.yaml, resources/postgresql/docker-compose-rabbitmq-postgresql-path-based-routing.yaml, resources/postgresql/docker-compose-rabbitmq-postgresql-redoer-rabbitmq-withinfo.yaml, resources/postgresql/docker-compose-rabbitmq-postgresql-redoer-rabbitmq.yaml, resources/postgresql/docker-compose-rabbitmq-postgresql-redoer-withinfo.yaml, resources/postgresql/docker-compose-rabbitmq-postgresql-ssl-auth.yaml, resources/postgresql/docker-compose-rabbitmq-postgresql-with-ELK.yaml, resources/postgresql/docker-compose-rabbitmq-postgresql-withinfo.yaml, resources/postgresql/docker-compose-rabbitmq-postgresql.yaml, resources/postgresql/docker-compose-sqs-postgresql-api-server.yaml, resources/postgresql/docker-compose-sqs-postgresql-redoer-sqs-withinfo.yaml, resources/postgresql/docker-compose-sqs-postgresql-redoer-sqs.yaml, resources/postgresql/docker-compose-sqs-postgresql-redoer-withinfo.yaml, resources/postgresql/docker-compose-sqs-postgresql-withinfo.yaml, resources/postgresql/docker-compose-sqs-postgresql.yaml
=> Issue 307.dockter.1

resources/postgresql/docker-compose-kafka-postgresql-api-server.yaml, resources/postgresql/docker-compose-kafka-postgresql-redoer-kafka-withinfo.yaml, resources/postgresql/docker-compose-kafka-postgresql-redoer-kafka.yaml, resources/postgresql/docker-compose-kafka-postgresql-redoer-withinfo.yaml, resources/postgresql/docker-compose-kafka-postgresql-withinfo.yaml, resources/postgresql/docker-compose-kafka-postgresql.yaml, resources/postgresql/docker-compose-postgresql-uninitialized.yaml, resources/postgresql/docker-compose-postgresql.yaml, resources/postgresql/docker-compose-rabbitmq-postgresql-api-server.yaml, resources/postgresql/docker-compose-rabbitmq-postgresql-backing-services-only.yaml, resources/postgresql/docker-compose-rabbitmq-postgresql-cluster.yaml, resources/postgresql/docker-compose-rabbitmq-postgresql-debug.yaml, resources/postgresql/docker-compose-rabbitmq-postgresql-migration.yaml, resources/postgresql/docker-compose-rabbitmq-postgresql-minimal.yaml, resources/postgresql/docker-compose-rabbitmq-postgresql-path-based-routing.yaml, resources/postgresql/docker-compose-rabbitmq-postgresql-redoer-rabbitmq-withinfo.yaml, resources/postgresql/docker-compose-rabbitmq-postgresql-redoer-rabbitmq.yaml, resources/postgresql/docker-compose-rabbitmq-postgresql-redoer-withinfo.yaml, resources/postgresql/docker-compose-rabbitmq-postgresql-ssl-auth.yaml, resources/postgresql/docker-compose-rabbitmq-postgresql-with-ELK.yaml, resources/postgresql/docker-compose-rabbitmq-postgresql-withinfo.yaml, resources/postgresql/docker-compose-rabbitmq-postgresql.yaml, resources/postgresql/docker-compose-sqs-postgresql-api-server.yaml, resources/postgresql/docker-compose-sqs-postgresql-redoer-sqs-withinfo.yaml, resources/postgresql/docker-compose-sqs-postgresql-redoer-sqs.yaml, resources/postgresql/docker-compose-sqs-postgresql-redoer-withinfo.yaml, resources/postgresql/docker-compose-sqs-postgresql-withinfo.yaml, resources/postgresql/docker-compose-sqs-postgresql.yaml
=> Issue 313.dockter.1

.github/CODEOWNERS, .github/dependabot.yml, .github/workflows/add-dependabot-request-to-project-t-comm.yaml, .github/workflows/add-issue-to-project-t-comm.yaml, .github/workflows/add-triage-label.yaml, .github/workflows/identify-customer.yaml, CHANGELOG.md, resources/mysql/docker-compose-kafka-mysql-api-server.yaml, resources/mysql/docker-compose-kafka-mysql.yaml, resources/mysql/docker-compose-rabbitmq-mysql-api-server.yaml, resources/mysql/docker-compose-rabbitmq-mysql.yaml
=> Issue 313.dockter.3

docs/common/advanced.md, docs/docker-compose-kafka-db2/README.md, docs/docker-compose-kafka-mssql/README.md, docs/docker-compose-kafka-mysql/README.md, docs/docker-compose-kafka-postgresql-advanced/README.md, docs/docker-compose-kafka-postgresql/README.md, docs/docker-compose-kafka-sqlite/README.md, docs/docker-compose-rabbitmq-db2/README.md, docs/docker-compose-rabbitmq-mssql/README.md, docs/docker-compose-rabbitmq-mysql/README.md, docs/docker-compose-rabbitmq-postgresql-advanced/README.md, docs/docker-compose-rabbitmq-postgresql-minimal/README.md, docs/docker-compose-rabbitmq-postgresql/README.md, docs/docker-compose-rabbitmq-sqlite-advanced/README.md, docs/docker-compose-rabbitmq-sqlite/README.md, docs/docker-compose-sqs-postgresql-advanced/README.md, docs/docker-compose-sqs-postgresql/README.md, resources/mssql/docker-compose-kafka-mssql-api-server.yaml, resources/mssql/docker-compose-kafka-mssql.yaml, resources/mssql/docker-compose-rabbitmq-mssql-api-server.yaml, resources/mssql/docker-compose-rabbitmq-mssql-cluster.yaml, resources/mssql/docker-compose-rabbitmq-mssql.yaml
=> Issue 313.dockter.4

docs/docker-compose-kafka-db2/README.md, docs/docker-compose-kafka-mssql/README.md, docs/docker-compose-kafka-mysql/README.md, docs/docker-compose-kafka-postgresql-advanced/README.md, docs/docker-compose-kafka-postgresql/README.md, docs/docker-compose-kafka-sqlite/README.md, docs/docker-compose-rabbitmq-db2/README.md, docs/docker-compose-rabbitmq-mssql/README.md, docs/docker-compose-rabbitmq-mysql/README.md, docs/docker-compose-rabbitmq-postgresql-advanced/README.md, docs/docker-compose-rabbitmq-postgresql-minimal/README.md, docs/docker-compose-rabbitmq-postgresql/README.md, docs/docker-compose-rabbitmq-sqlite-advanced/README.md, docs/docker-compose-rabbitmq-sqlite/README.md, docs/docker-compose-sqs-postgresql-advanced/README.md, docs/docker-compose-sqs-postgresql/README.md
=> #324 Update links

README.md
=> #330 Add warning

resources/postgresql/docker-compose-rabbitmq-postgresql-web-app-demo.yaml
=> #345 Initial draft

resources/postgresql/docker-compose-rabbitmq-postgresql-web-app-demo.yaml
=> #345 Trim down unused docker containers

resources/mssql/docker-compose-mssql-only.yaml, resources/mysql/docker-compose-mysql-only.yaml, resources/oracle/docker-compose-oracle-only.yaml, resources/postgresql/docker-compose-postgresql-only.yaml
=> #353 Database-only example

resources/postgresql/docker-compose-postgresql-with-runtime.yaml
=> #355 Demo using senzing/senzingapi-runtime
